### ISSUE TITLE
Showing SysAdmin in OpenEdx Navigation Bar.

### ISSUE THREAD

**Issue by asadiqbal08** [mitodl/edx-sysadmin#1]
We need to show the "SysAdmin" tab in the navbar and render the App templates upon clicking on it. 

- [ ] A PR in OpenEdx to show the SysAdmin label if the application is installed in the system. e.g. `/sysadmin/`
- [ ] The sysadmin tab should only be visible to django admins (except for the gitlogs function)

**Comment by HamzaIbnFarooq** [comment]
**Existing behavior**:
Currently, Sysadmin dashboard is shown when `ENABLE_SYSADMIN_DASHBOARD` is set to `True` via an environment variable.

**Behavior we want to achieve**:
Sysadmin Dashboard should only be shown if and only if `edx-sysadmin` plugin is installed.

**Question**:
If Sysadmin's visibility is dependent on `edx-sysadmin` plugin, do we want the `ENABLE_SYSADMIN_DASHBOARD` flag to be an explicit control point (to disable/enable the feature through environment variables)? In simple words, if sysadmin is installed it will remain visible until or unless you delete it from the server, it will not be controlled by environment .yml files.

**Solutions**:
**If we want the explicit flag** then we need to add a `new variable` OR `check every time` if `edx-sysadmin` is present in `INSTALLED_APPS`.
**If we don't want that explicit flag** then we can use the same `ENABLE_SYSADMIN_DASHBOARD` flag, cut its connection from environment yml files and turn it on through our plugin. In this way most of the checks in Open edX will remain the same.

@pdpinch do you have any thoughts on it?

**Comment by pdpinch** [comment]
I don’t see any reasons to maintain the explicit flag. 

I guess this option makes sense and is the least risky change: 

> If we don't want that explicit flag then we can use the same ENABLE_SYSADMIN_DASHBOARD flag, cut its connection from environment yml files and turn it on through our plugin. In this way most of the checks in Open edX will remain the same.
>

**Comment by HamzaIbnFarooq** [comment]
@pdpinch 
In https://github.com/mitodl/edx-sysadmin/issues/4 you have mentioned that `Access to git import and git logs should be limited to course admins`. Can you define what `course-admin` term refers to? and just, to confirm, we have to restrict superuser from git log features?

Secondly, under the `Instructor tab` of `course` there is a link saying `View detailed Git import logs for this course by clicking here.` which takes user to sysadmin dashboard's git-log feature (even if the course wasn't loaded through git). Do we have to keep this feature?
![image](https://user-images.githubusercontent.com/42243411/112632978-9d2b6600-8e5a-11eb-8fa9-2e3d8c183854.png)

**Comment by pdpinch** [comment]
> Access to git import and git logs should be limited to course admins. Can you define what course-admin term refers to? and just, to confirm, we have to restrict superuser from git log features?

1. Don't restrict superuser
2. "course admin" is anyone with the admin role in the course, for example, [in studio](https://studio-staging.mitx.mit.edu/course_team/course-v1:TestX+Test101+2T2020): 
<img width="977" alt="image" src="https://user-images.githubusercontent.com/430126/112991287-f2a29400-9134-11eb-9c6d-4f70609050de.png">

**Comment by pdpinch** [comment]
>Secondly, under the Instructor tab of course there is a link saying View detailed Git import logs for this course by clicking here. which takes user to sysadmin dashboard's git-log feature (even if the course wasn't loaded through git and even if the user is not is_staff). Do we have to keep this feature?
image

This link is a convenience, but as you note it isn't properly implemented. Let's drop it for now, but can you open an issue to add it back as an enhancement?

**Comment by HamzaIbnFarooq** [comment]
Issue has been closed by https://github.com/mitodl/mitx-theme/pull/132
