### ISSUE TITLE
[Phase 3] Switch from Mongo to MySQL

### ISSUE THREAD

**Issue by umarmughal824** [mitodl/edx-sysadmin#12]
[Phase 3] Switch from Mongo to MySQL

### Acceptance criteria
- [ ] Git Logs should be stored in MySQL instead of Mongo 
- [ ] Need to update git import part for that specific issue

**Comment by HamzaIbnFarooq** [comment]
This issue has been solved by https://github.com/mitodl/edx-sysadmin/pull/27
