### ISSUE TITLE
[Phase 3] Add git import management command

### ISSUE THREAD

**Issue by HamzaIbnFarooq** [mitodl/edx-sysadmin#15]
### Description

Move `Git Course Import management command` from [edx-platform](https://github.com/edx/edx-platform/tree/open-release/koa.master/lms/djangoapps/dashboard/management/commands) to sysadmin plugin.

### Acceptance Criteria

- [ ] Move command and make it functional
- [ ] Move and fix tests

**Comment by umarmughal824** [comment]
@HamzaIbnFarooq I had added management command and it was functional too. Why we need the separate ticket for it now?

**Comment by HamzaIbnFarooq** [comment]
@umarmughal824 have all the acceptance criterias of this ticket fulfilled?

**Comment by HamzaIbnFarooq** [comment]
Git-Import management command is in place and its tests have been added by https://github.com/mitodl/edx-sysadmin/pull/19
