### ISSUE TITLE
[Phase 3] Add permission based feature access

### ISSUE THREAD

**Issue by HamzaIbnFarooq** [mitodl/edx-sysadmin#16]
### Description
Currently, sysadmin has four main features:
1) User Creation
2) Course Deletion
3) Git Course Import
4) Git Course Import Logs
We need to hide/show tabs to users on the basis of their permissions.

### Acceptance Criteria
- [ ] Allow `Superuser` to access all features
- [ ] `Course-Admins` can view `Git Course Import Logs` for courses they have access to
- [ ] `Course-Admins` can view `Git Course Import` and import a course for courses they have access to 

### Q/A
**_Q:_** What is a Course-Admin role?
**_A:_** `Course Admin` is [Course Instructor](https://github.com/edx/edx-platform/blob/open-release/koa.master/common/djangoapps/student/roles.py#L260). This role can be assigned through `Course Team Management` under `Membership` tab under `Instructor` tab of a course.

_**Q:**_ `Course Admin` is `admin of a specific course`, it's not a global role (e.g course creator is a global role). Do we want to allow him to create new courses by allowing him access to `Git Course Import`?
**_A:_** **No. We should only give the course admin access to `Git Course Import` if they can be prevented from creating new courses**

**_Q:_** Can `Course Admin` view `Git Course Import Logs` of all the courses of platform? or just the ones having him as a `Course Admin`?
**_A:_** **The course admin can only view import logs for courses they have access to**

**Comment by pdpinch** [comment]
I updated the description and answered the questions. Let me know if it needs any further clarification.

**Comment by HamzaIbnFarooq** [comment]
> Q: Course Admin is admin of a specific course, it's not a global role (e.g course creator is a global role). Do we want to allow him to create new courses by allowing him access to Git Course Import?
>A: Yes, but only if we can limit the import to courses the course admin already has access to

@pdpinch  When you say `if we can limit the import to courses the course admin already has access to` it seems like you don't want to allow the creation of new courses with `git import`, rather you want the old courses to get updated through it. Am I thinking in the right direction?

**Comment by pdpinch** [comment]
@HamzaIbnFarooq You're right, sorry. I edited the description to be clearer. Only django superuser should be able to create new courses. If we can't limit course admins to importing into existing courses, then we shouldn't give them access to Git Course Import.

**Comment by HamzaIbnFarooq** [comment]
As per the discussion above, I tried to allow Course-Admins to update their courses from git using the Git-Import feature while restricting them from creating a new course using the same feature but that's not possible because until the course repo is fetched and the course is created on Open edX, we can't tell if the user has entered a new git repo link or updated an existing course. Thus we have to restrict Course-Admins from the whole Git-Import feature.

cc: @pdpinch

**Comment by pdpinch** [comment]
Thanks for trying Hamza. I understand the constraint.

**Comment by pdpinch** [comment]
When this issue is closed, I think we should do a PyPI release, to make it easier for @mitodl/devops to deploy.

**Comment by HamzaIbnFarooq** [comment]
closed by https://github.com/mitodl/edx-sysadmin/pull/23
