### ISSUE TITLE
[SysAdmin] Create User Functionality

### ISSUE THREAD

**Issue by asadiqbal08** [mitodl/edx-sysadmin#2]
Keep it simple at the time being. 

- [ ] Move the create user functionality from OpenEdx to sysadmin Django application.
- [ ] Use the user-creation API endpoint for creating user. i.e. "/user_api/v1/account/registration/"
- [ ] Create a template for creating user.

**Comment by HamzaIbnFarooq** [comment]
I found the following caveats while exploring `/user_api/v1/account/registration/` API:
* We have to fulfill all the fields specified for account registration depending upon what `settings.REGISTRATION_EXTRA_FIELDS` value is.
* `settings.FEATURES['ALLOW_PUBLIC_ACCOUNT_CREATION’]` must be `True`

#### For xpro only.
* `ENABLE_REQUIRE_THIRD_PARTY_AUTH` must be `False`. 

### Solution
The solution can be to do the same as what sysadmin is doing right now, which is to directly create users through edX's helper methods.

**Comment by pdpinch** [comment]
Does this [edx-platform PR](https://github.com/edx/edx-platform/pull/25935) change our options at all?

**Comment by HamzaIbnFarooq** [comment]
@pdpinch yes that seems like a valid solution But if we use `is_require_third_party_auth_enabled` method which is based on `ENABLE_REQUIRE_THIRD_PARTY_AUTH` we won't be able to use the `/user_api/v1/account/registration/` API. But obviously, the SSO issue will be solved.

**Comment by HamzaIbnFarooq** [comment]
To add more context to my above comment, here is the link to registration API's POST method: https://github.com/edx/edx-platform/blob/master/openedx/core/djangoapps/user_authn/views/register.py#L503

**Comment by HamzaIbnFarooq** [comment]
Closed By https://github.com/mitodl/edx-sysadmin/pull/9
