### ISSUE TITLE
Add possible fixes for the Warnings

### ISSUE THREAD

**Issue by arslanashraf7** [mitodl/edx-sysadmin#21]
There are a few `pytest` warnings that we might need to have a deeper look at and add any possible fixes for them.

These warnings are mostly thrown from inside the edX which could automatically be fixed when they are fixed in edX itself but we have to check if there are any that we can fix. The warnings are ignored [here](https://github.com/mitodl/edx-sysadmin/pull/19/files#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449R36).

A screenshot is added for reference below:

<img width="1436" alt="Screenshot 2021-04-12 at 1 53 58 PM" src="https://user-images.githubusercontent.com/34372316/114368377-ce17d480-9b96-11eb-8532-4dbbeb27d270.png">

**Comment by pdpinch** [comment]
Is this still an issue?

**Comment by arslanashraf7** [comment]
@pdpinch, Looking at the current stats on [github actions](https://github.com/mitodl/edx-sysadmin/runs/2674557351#step:7:1457) it looks like this is still an issue.

Additionally, Some of the warnings were added to the ignored list at that time in a [commit](https://github.com/mitodl/edx-sysadmin/pull/19/files#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449R36) and we can check about which of the ignored ones we can remove/fix.

**Comment by Anas12091101** [comment]
@arslanashraf7 can we close this now?

**Comment by arslanashraf7** [comment]
@Anas12091101 I am not sure. We will have to run the plugin and analyze the logs. Can you try it?

**Comment by Anas12091101** [comment]
I checked the logs in the [latest CI run](https://github.com/mitodl/open-edx-plugins/actions/runs/10023352948/job/27704161311) in open-edx-plugins and I didn't find any warning related to this plugin. Most of the warnings are from site-packages and some are from edx-platform. Closing this issue as completed.
