### ISSUE TITLE
Publish edx-sysadmin to PyPI

### ISSUE THREAD

**Issue by HamzaIbnFarooq** [mitodl/edx-sysadmin#25]
For easy access and testing we need to publish this to PyPI as mentioned in the comment https://github.com/mitodl/edx-sysadmin/issues/16#issuecomment-821220296

**Comment by pdpinch** [comment]
@blarghmatey @annagav have we worked out how to set up publishing to PyPI with concourse?

**Comment by annagav** [comment]
@pdpinch what is the idea behind using concourse for this instead of doof? Do we need automated uploads to PyPI for every new commit? are we planning to do that for other packages?

**Comment by blarghmatey** [comment]
The motivation is to eliminate the manual steps involved in building and publishing a release, and also to remove the need to add all of the supporting infrastructure to make Doof handle publishing of library packages. With Concourse we should be able to just write a pipeline template for Python packages and create an instance of it any time we have a new project that needs to use it. Similarly for NPM.

**Comment by blarghmatey** [comment]
And yes, ideally we should be able to build and publish a new package automatically whenever we push to master.

**Comment by annagav** [comment]
@blarghmatey @pdpinch I am going to create a release branch so that we can control the release process and update the version number, and the pipeline be triggered to  build and publish whenever there is new commit on release branch.

**Comment by pdpinch** [comment]
Can this issue be closed?
