### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS error when trying to access SYSADMIN as a user w/o permissions

### ISSUE THREAD

**Issue by briangrossman** [mitodl/edx-sysadmin#28]
Prior to being granted access to the SYSADMIN on `qa.mitx.mit.edu/sysadmin/`, I received the ERR_TOO_MANY_REDIRECTS error when trying to log in.

### Steps to Reproduce
- Sign in as a user who does not have access to `/sysadmin/`
- Try to access `/sysadmin/`
- The browser will redirect you to  `/login?next=/sysadmin/` and give you the error below:

![image](https://user-images.githubusercontent.com/21342568/116588356-7513a480-a8e9-11eb-8649-c99e493f87b8.png)

### Expected Behavior

It should behave like other pages to which the user doesn't have access. I believe it usually shows a `Page not found` error:
![image](https://user-images.githubusercontent.com/21342568/116589459-ab055880-a8ea-11eb-8119-39b7f710150e.png)

**Comment by pdpinch** [comment]
@HamzaIbnFarooq @briangrossman can this be closed?

**Comment by HamzaIbnFarooq** [comment]
As per my testing, this issue has been solved but I would like to have Brian's feedback on it as well.

**Comment by briangrossman** [comment]
I also tested on `mitx-qa-next` (using Hamza's strategy - below) and confirmed I didn't see the issue. I'm closing this.

Steps for testing
- Create a new user through Sysadmin's User tab
- Go to admin panel and add superuser and staff permissions to the newly created account
- In an incognito window, login as that user and go to the sysadmin dash
- Remove the user's staff and superuser status
- Try accessing sysadmin as that user
