### ISSUE TITLE
Users : Password field is cleartext

### ISSUE THREAD

**Issue by briangrossman** [mitodl/edx-sysadmin#33]
In the `Users` tab, when you enter your password, it's cleartext. It should be obscured.

![image](https://user-images.githubusercontent.com/21342568/119175545-f4534e80-ba37-11eb-9547-9dd950c6bf99.png)

**Comment by HamzaIbnFarooq** [comment]
FYI: The thought behind keeping it cleartext was that it would be easy for the sysadmin to check the password and easily copy-paste it where ever he wants to. Now I am changing it to a password field.

cc: @briangrossman

**Comment by briangrossman** [comment]
> FYI: The thought behind keeping it cleartext was that it would be easy for the sysadmin to check the password and easily copy-paste it where ever he wants to. Now I am changing it to a password field.
> 
> cc: @briangrossman

Thanks, @HamzaIbnFarooq 
I see. Let's just keep it as a password field for now.

**Comment by HamzaIbnFarooq** [comment]
Closed by https://github.com/mitodl/edx-sysadmin/pull/36
