### ISSUE TITLE
Users : Fields should clear on success

### ISSUE THREAD

**Issue by briangrossman** [mitodl/edx-sysadmin#34]
When you successfully register via the `Users` tab, the fields should clear. Currently they continue to show the entered text.

![image](https://user-images.githubusercontent.com/21342568/119175949-7b082b80-ba38-11eb-897b-e03be58ed463.png)

**Comment by HamzaIbnFarooq** [comment]
Closed by https://github.com/mitodl/edx-sysadmin/pull/38
