### ISSUE TITLE
[SysAdmin] Git Import and GitLogs Functionality

### ISSUE THREAD

**Issue by asadiqbal08** [mitodl/edx-sysadmin#4]
- [ ] Move the Git import logic from OpenEdx to SysAdmin.
- [ ] Need to define a model in SysAdmin same fields as `CourseImportLog` but instead pointing to Mongo, it should be to MySql model. 
- [ ] Update the git_import.py file accordingly
- [ ] Access to git import and git logs should be limited to course admins. 

#### NOTE: 
- It still have dependency in OpenEdx as I can `CourseLocator` there. 
- Performance Impact in case of storing data in SQL Model. (Tech Debate)

**Comment by pdpinch** [comment]
I add an acceptance criteria to the description about access control. A course admin should be able to view the gitlogs for their course, but not others. 

If possible, a course admin should be able to import their course from git. This may be complicated though because I don't think we know which course is being imported until the import starts.

**Comment by pdpinch** [comment]
Possibly relevant work going on at edX regarding logging courseware errors: https://github.com/edx/edx-platform/pull/26987

**Comment by umarmughal824** [comment]
@pdpinch Could you provide a sample course for `Load new course from Github` that will be required to test the git logs functionality.

Currently, on our local edX setup, the `GitLogs` page is not working either. Need to troubleshoot too.

**Comment by pdpinch** [comment]
I'm not sure how old edx4edx_lite is... can you access [this test course](https://github.mit.edu/mitx/content-devops-0001)? (also old, but not _as_ old).

There's also test data in the edx-platform repo. It probably makes sense for us to set up a standalone repo with the contents of https://github.com/edx/edx-platform/tree/master/common/test/data/test_import_course

**Comment by umarmughal824** [comment]
@pdpinch thanks, I will try it out.

**Comment by umarmughal824** [comment]
@pdpinch [this test course](https://github.mit.edu/mitx/content-devops-0001) is not accessible.

**Comment by pdpinch** [comment]
Can this be closed now that #8 and #10 have merged?

I know that the permissions work is not done, but we have a separate issue #16 for that.

**Comment by pdpinch** [comment]
@umarmughal824 do you think this can be closed?

**Comment by umarmughal824** [comment]
yeah
