### ISSUE TITLE
Change the default user creation flow

### ISSUE THREAD

**Issue by HamzaIbnFarooq** [mitodl/edx-sysadmin#40]
### Description

In **Old Sysadmin**, users were created through `django.contrib.auth.models.User` so we only needed `username, full name, email address, and password` for account creation.

While in **edx-sysadmin** we thought to keep the old flow as well as to add a new one:
1) Directly creating user account through `django.contrib.auth.models.User` (_Old flow_)
2) Using edX's Registration API for account creation (_This one is kept **default** as using APIs was supposed to be the priority_)

**Both the approaches have been explained in the description and testing details of** #9 

#### Caveats of edX's Registration API
The Registration API came with some limitations and dependencies:
1) `settings.ENABLE_REQUIRE_THIRD_PARTY_AUTH` should be set `False`
2) `settings.FEATURES['ALLOW_PUBLIC_ACCOUNT_CREATION']` should be set `True`
3) All `required` fields present in `settings.REGISTRATION_EXTRA_FIELDS` should be provided to execute the API call.

**Points 1 & 2** were quite clear so we decided to run the _old method_ if those variables were not set properly. 

**Point no. 3** makes some ambiguity as it introduces some new fields to the account creation process although we didn't need those in the old sysadmin, the extra fields can be any of the following (set through environment files like `lms.yml`)
```
REGISTRATION_EXTRA_FIELDS = {
    "city": "required",
    "confirm_email": "required",
    "country": "required",
    "gender": "required",
    "goals": "required",
    "honor_code": "required",
    "level_of_education": "required",
    "mailing_address": "required",
    "terms_of_service": "required",
    "year_of_birth": "required",
}
```

#### Current Issue and most probable solution
After multiple discussions, I have found that most of the users of this application might not like the idea of newly added fields rather they would like to stick to the old-styled account creation instead of using the Registration API. 

If my understanding of the issue is correct then we can change the default account creation method to `Directly creating a user account through **django.contrib.auth.models.User** (_Old flow_)` and put `Registration API (_New flow_)` behind a new environment flag in case someone would like to use it to create the users.

In this way, users will see the old sysadmin behavior, until or unless they themselves activate the new flag.

**Comment by HamzaIbnFarooq** [comment]
@pdpinch @briangrossman kindly have a look into this issue to discuss the account creation process in depth.

**Comment by pdpinch** [comment]
Thanks for this right up. I think we need to talk to some users and review the use cases before we can properly answer these questions. 

1. Residential MITx
2. xPRO
3. Others?

**Comment by pdpinch** [comment]
It looks like we are setting these fields in residential here:

https://github.com/mitodl/salt-ops/blob/1072ac613c748a9608cb35c3232de5f35d59e484/pillar/edx/ansible_vars/residential.sls#L108-L118

and in xPRO here:

https://github.com/mitodl/salt-ops/blob/1072ac613c748a9608cb35c3232de5f35d59e484/pillar/edx/ansible_vars/xpro.sls#L61-L71

In both cases, we should change `honor_code: "required"` to `honor_code: "hidden"`

**Comment by briangrossman** [comment]
@HamzaIbnFarooq 

Thanks for walking me through these options today. What you're proposing is a good solution. Let's proceed with it:
- Default to the old flow `django.contrib.auth.models.User`
- Keep the new flow `Registration API` as an option behind a flag
- Update the README to include details on how to switch the flow

**Comment by Anas12091101** [comment]
@pdpinch can we close this issue? I think it's not relevant anymore
