### ISSUE TITLE
Standardize UX/UI for error and confirmation messages

### ISSUE THREAD

**Issue by briangrossman** [mitodl/edx-sysadmin#42]
There are a few different css treatments for the error and confirmation messages in the Sysadmin dashboard. We should standardize. If possible, leverage CSS from the rest of edX for styling error / confirmation messages. 

e.g. from edX:
![image](https://user-images.githubusercontent.com/21342568/120702960-b536eb80-c482-11eb-8536-27edd9eec583.png)

---

**Samples from the sysadmin dash**

Register Users
![image](https://user-images.githubusercontent.com/21342568/120702373-01356080-c482-11eb-99b6-8ce10e2ee381.png)

Delete Course
![image](https://user-images.githubusercontent.com/21342568/120702419-0db9b900-c482-11eb-9aee-6f954580dd15.png)

Import Course
![image](https://user-images.githubusercontent.com/21342568/120702493-232ee300-c482-11eb-89e6-7b0a3ee1acc5.png)

Related to: #41

**Comment by arslanashraf7** [comment]
Closing, Associated PR has been merged. We can reopen if we see if there's an issue with this.
