### ISSUE TITLE
accept sha1 signatures on webhoooks

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-sysadmin#59]
GitHub enterprise at MIT sends webhooks with a sha1 header. We are asking IS&T to upgrade, but in the meantime, we should have a fallback to accept sha1 when sha256 isn't available. 

https://github.com/mitodl/edx-sysadmin/blob/066256d3af12c0471aa9e060664506ae50016bf9/edx_sysadmin/api/permissions.py#L52-L54

**Comment by arslanashraf7** [comment]
Closed via #60
