### ISSUE TITLE
Move edx-sysadmin plugin to open-edx-plugins

### ISSUE THREAD

**Issue by shaidar** [mitodl/edx-sysadmin#76]
We now have a [repo](https://github.com/mitodl/open-edx-plugins) that includes our openedx-plugins and we should move this one there and make it part of that repo.

**Comment by arslanashraf7** [comment]
@pdpinch FYI. Regarding the complexity.

I looked around the repository components and I think this transition should be relatively straightforward and not face any major blockers except for the frontend templates, signals migration, and integration test fixes based on:

1. Some of the plugin architecture configurations are already in place which might need some simple tweaks and they should be all set.
2. Settings are also placed in a way that aligns with the plugin architecture.
3. We might need to write configuration files for the templates to be served through the plugin itself.
4. We recently added some signal-based fixes, we'll need to get them out of setup.py files and make those configurations generatable through the pants build system( in open-edx-plugins).
5. Currently, integration tests are failing we might need to make reasonable tweaks in that to get them running again.

At this point, I think all of these are doable with a moderate effort.

**Comment by pdpinch** [comment]
@arslanashraf7 can you remind me of the status of this?

**Comment by arslanashraf7** [comment]
> @arslanashraf7 can you remind me of the status of this?

@pdpinch The migration is complete. The sysadmin package gets built using `pants` build system under the `dist` directory just like other plugins here. It can be installed and work just like it used to. We kept the package name the same so it would get installed on the existing package.

**About Tests:**
The test suit has also been migrated here but that doesn't run for now. We will need to configure `pants` to integrate the tests for all open-edx-plugins at some point along with sysadmin plugin tests. All this should be done in a separate ticket that would enable running tests on all the plugins in this mono repo.

**Comment by arslanashraf7** [comment]
.. I can create a ticket to configure `pants` to run the tests in Github Actions throughout all the packages. And i'll merge and close other ticket like https://github.com/mitodl/edx-sysadmin/pull/85 on Monday.

**Comment by arslanashraf7** [comment]
> .. I can create a ticket to configure `pants` to run the tests in Github Actions throughout all the packages. And i'll merge and close other ticket like #85 on Monday.

I've created the ticket https://github.com/mitodl/open-edx-plugins/issues/212. The rest is done via https://github.com/mitodl/open-edx-plugins/pull/192.
